### ISSUE TITLE
关于ACTION工作流最近不工作

### ISSUE THREAD

**Issue by koinin** [hx-w/scu-covid-auto-checkin#2]
从您这fork的workflow 最近不工作了，我查看了一下，从五天前就开始不工作，我尝试更换了cookie 但是还是不能启动ACTION

**Comment by hx-w** [comment]
![image](https://user-images.githubusercontent.com/32268783/149620583-06f2957c-a2f1-46a3-b2f6-5dfb8787e730.png)
github对开启actions的态度比较保守，fork后长时间没有更新会关闭actions，需要手动点开。

顺带寒假可能会更新一些更完善的功能，目前的太简陋了。

**Comment by koinin** [comment]
您好，您的来信我已收到，我会尽快处理您的邮件谢谢

**Comment by koinin** [comment]
好的，谢谢楼主
